@echo off
setlocal enabledelayedexpansion

title Package DesktopClock
cd /d "%~dp0"

echo.
echo ============================================
echo   Desktop Clock -- PyInstaller Packager
echo ============================================
echo.

:: Check Python
where python >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Python not found. Please install Python 3.8+
    pause
    exit /b 1
)
echo [OK] Python found

:: Check/Install PyInstaller
python -c "import PyInstaller" >nul 2>&1
if %errorlevel% neq 0 (
    echo [INFO] Installing PyInstaller...
    pip install pyinstaller -q
    if %errorlevel% neq 0 (
        echo [ERROR] Failed to install PyInstaller
        pause
        exit /b 1
    )
    echo [OK] PyInstaller installed
) else (
    echo [OK] PyInstaller already installed
)

:: Clean old output only (dist and build are regenerated by PyInstaller)
if exist "dist" rmdir /s /q "dist"

:: Package
echo.
echo [START] Packaging, please wait...
echo.
python -m PyInstaller --onefile --windowed --name "DesktopClock" --distpath "dist" --workpath "build" --specpath "." --clean "main.py"

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Packaging failed
    pause
    exit /b 1
)

:: Clean temp
if exist "build" rmdir /s /q "build"
if exist "DesktopClock.spec" del /q "DesktopClock.spec"

:: Copy EXE to current folder
if exist "dist\DesktopClock.exe" (
    copy /y "dist\DesktopClock.exe" "DesktopClock.exe" >nul
    echo.
    echo ============================================
    echo   [SUCCESS] Packaging complete!
    echo ============================================
    echo.
    echo Output files:
    echo   - dist\DesktopClock.exe
    echo   - DesktopClock.exe (current dir)
    echo.
    echo Next: run install_shortcut.ps1 to create shortcuts
    echo.
) else (
    echo [ERROR] EXE not found
    pause
    exit /b 1
)

pause